<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_length" value="0.6"/>
    <xacro:property name="base_width" value="0.4"/>
    <xacro:property name="base_height" value="0.2"/>
    <xacro:property name="wheel_radius" value="0.1"/>
    <xacro:property name="wheel_length" value="0.05"/>
    
    <link name="footprint_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"></origin>
        </visual>
    </link>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"></box>
            </geometry>
            <origin xyz="0 0 ${base_height / 2}" rpy="0 0 0"></origin>
            <material name="green"/>
        </visual>
    </link>

    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0"></origin>
                <material name="gray"/>
            </visual>
        </link>
    </xacro:macro>

    <xacro:wheel_link prefix="right"/>

    <xacro:wheel_link prefix="left"/>

    <link name="caster_wheel">
        <visual>
            <geometry>
                <sphere radius="${wheel_radius / 2}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"></origin>
            <material name="gray"/>
        </visual>
    </link>

    <joint name="base_right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel_link"/>
        <origin xyz="${-base_length / 4.0} ${-(base_width+wheel_length)/2} 0.0" rpy="${pi / 2.0} 0.0 0.0"/>
        <axis xyz="0.0 0.0 -1"/>
    </joint>

    <joint name="base_left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel_link"/>
        <origin xyz="${-base_length / 4.0} ${(base_width+wheel_length)/2} 0.0" rpy="${pi / 2.0} 0.0 0.0"/>
        <axis xyz="0.0 0.0 -1"/>
    </joint>

    <joint name="base_caster_wheel_joint" type="fixed">
        <origin xyz="${base_length/3.0} 0.0 ${-wheel_radius/2}" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="caster_wheel"/>
    </joint>

    <joint name="base_footprint_joint" type="fixed">
        <origin xyz="0.0 0.0 ${wheel_radius}" rpy="0.0 0.0 0.0"/>
        <parent link="footprint_link"/>
        <child link="base_link"/>
    </joint>

</robot>